{ config, lib, pkgs, ... }:

{
  boot.kernelParams = [ "quiet" ];
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  # Init amdgpu in the initrd so the Radeon 780M is up before userspace —
  # EWM launches from tty1 autologin and loses the DRM-master race otherwise
  # (verified on zord-old).
  boot.initrd.kernelModules = [ "amdgpu" ];

  # Wifi (Qualcomm NFA765) + amdgpu need redistributable firmware — nixos-hardware
  # does NOT set this, so keep it here (verified: dropping it left the option false).
  hardware.enableRedistributableFirmware = true;

  # AMD pstate (amd_pstate=active), the s2idle acpi.ec_no_wakeup fix, and other
  # tuning come from nixos-hardware's lenovo-thinkpad-t14-amd-gen5 (flake.nix).

  # Disk layout (fileSystems + boot.initrd.luks.devices) is GENERATED by the
  # disko module from hosts/zord/disko.nix. Do NOT hand-write it here — a
  # second definition collides with disko's by-partlabel paths and the whole
  # config fails to evaluate. This file is hardware only.
  # Audio, Bluetooth, touchpad, and the bootloader live in desktop.nix.

  powerManagement.enable = true;
  services.power-profiles-daemon.enable = true;
}
