#!/usr/bin/env python3
"""Assert the load-bearing literals of an emanix disk layout, BY NAME.

Why this exists, given tests/disk-layout.sh already diffs against fixtures:
the fixtures are generated by the code under test, so the only thing standing
between a mistranscribed layout and a green suite was a byte count. A byte
count is a four-digit checksum, and the mistakes that matter here are
length-preserving:

    type = "EF00"      -> "8300"   /boot is no longer an EFI System Partition
    fmask=0077         -> fmask=0000   world-readable ESP
    mountpoint "/nix"  -> "/var"   nix store mounted at the wrong subvolume
    size = "1G"        -> "9G"

Every one of those regenerates to a fixture of exactly the same size, and the
result is a machine that installs and then does not boot -- or boots wrong --
with the disk already destroyed. So the literals are named here, structurally,
and this script is run against BOTH the generated output (drift) and the
committed fixture (a bad re-baseline). It is invoked from tests/disk-layout.sh
and, so that it runs without anyone remembering to, from checks/disk-layout.nix
on every `nix flake check`.

usage: disk-layout-literals.py LABEL FILE.json
The JSON is the `disko.devices` attrset mkDisk produces.
"""
import json
import sys

failures = []


def eq(what, got, want):
    if got != want:
        failures.append(f"{what}: expected {want!r}, got {got!r}")


def main(label, path):
    with open(path) as fh:
        devices = json.load(fh)

    disk = devices["disk"]["main"]
    eq("disk.main.type", disk.get("type"), "disk")

    table = disk["content"]
    eq("partition table", table.get("type"), "gpt")

    parts = table["partitions"]

    # The ESP. EF00 is what makes firmware treat this as an EFI System
    # Partition; 8300 (plain Linux filesystem) is the same four characters and
    # a machine that will not boot.
    boot = parts["boot"]
    eq("boot partition type", boot.get("type"), "EF00")
    eq("boot partition size", boot.get("size"), "1G")
    eq("boot filesystem", boot["content"].get("format"), "vfat")
    eq("boot mountpoint", boot["content"].get("mountpoint"), "/boot")
    opts = boot["content"].get("mountOptions", [])
    if "fmask=0077" not in opts:
        failures.append(f"boot mountOptions: fmask=0077 missing, got {opts!r}")
    if "dmask=0077" not in opts:
        failures.append(f"boot mountOptions: dmask=0077 missing, got {opts!r}")

    # The root partition fills the disk. Anything else silently strands space
    # or, worse, overlaps nothing and installs into a fraction of the drive.
    root = parts["root"]
    eq("root partition size", root.get("size"), "100%")

    # LUKS wraps the filesystem rather than replacing it, so unwrap one layer
    # when it is there. Both shapes must produce the same mountpoints.
    content = root["content"]
    if content.get("type") == "luks":
        eq("luks mapper name", content.get("name"), "cryptroot")
        content = content["content"]

    if content.get("type") == "btrfs":
        subvols = content["subvolumes"]
        for name, mountpoint in (("@", "/"), ("@nix", "/nix"), ("@home", "/home")):
            if name not in subvols:
                failures.append(f"subvolume {name!r} is missing entirely")
                continue
            eq(f"subvolume {name} mountpoint", subvols[name].get("mountpoint"), mountpoint)
    else:
        eq("non-btrfs root format", content.get("format"), "ext4")
        eq("non-btrfs root mountpoint", content.get("mountpoint"), "/")

    if failures:
        print(f"FAIL literals {label}:")
        for f in failures:
            print(f"       {f}")
        return 1
    print(f"ok   literals {label}")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__.strip().splitlines()[-2], file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1], sys.argv[2]))
