# Catppuccin Mocha palette — human reference (not consumed by dot-theme-set)
# Source: https://catppuccin.com/palette
export CATPPUCCIN_ROSEWATER="#f5e0dc"
export CATPPUCCIN_FLAMINGO="#f2cdcd"
export CATPPUCCIN_PINK="#f5c2e7"
export CATPPUCCIN_MAUVE="#cba6f7"
export CATPPUCCIN_RED="#f38ba8"
export CATPPUCCIN_MAROON="#eba0ac"
export CATPPUCCIN_PEACH="#fab387"
export CATPPUCCIN_YELLOW="#f9e2af"
export CATPPUCCIN_GREEN="#a6e3a1"
export CATPPUCCIN_TEAL="#94e2d5"
export CATPPUCCIN_SKY="#89dceb"
export CATPPUCCIN_SAPPHIRE="#74c7ec"
export CATPPUCCIN_BLUE="#89b4fa"
export CATPPUCCIN_LAVENDER="#b4befe"
export CATPPUCCIN_TEXT="#cdd6f4"
export CATPPUCCIN_SUBTEXT1="#bac2de"
export CATPPUCCIN_SUBTEXT0="#a6adc8"
export CATPPUCCIN_OVERLAY2="#9399b2"
export CATPPUCCIN_OVERLAY1="#7f849c"
export CATPPUCCIN_OVERLAY0="#6c7086"
export CATPPUCCIN_SURFACE2="#585b70"
export CATPPUCCIN_SURFACE1="#45475a"
export CATPPUCCIN_SURFACE0="#313244"
export CATPPUCCIN_BASE="#1e1e2e"
export CATPPUCCIN_MANTLE="#181825"
export CATPPUCCIN_CRUST="#11111b"
