{ config, lib, pkgs, ... }:

{
  options.eminix.pi = {
    settingsSource = lib.mkOption {
      type = lib.types.path;
      default = ./pi/agent/settings.json;
      description = ''
        Path to the pi agent settings.json used to SEED ~/.pi/agent/settings.json.
        Defaults to the distro's generic file. Consumers that want their own
        model/provider choices point this at a file in their own checkout.
      '';
    };
  };

  config = {
    # Pi coding agent configuration.
    # Pi itself is installed declaratively via packages.nix (pi-coding-agent from
    # nixpkgs). This module only manages the config files.
    # settings.json is SEEDED, not owned: pi mutates it at runtime (model
    # toggles, lastChangelogVersion), so a read-only store symlink breaks pi —
    # and without the real file's `packages` list, pi loads no extensions at
    # all (found 2026-07-13: zord-old had a {theme,model} stub → no hindsight
    # bar). After the first activation the machine's copy is authoritative;
    # it is stignored from the pi-agent sync, so per-machine drift is fine.
    home.activation.piSettingsSeed = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      if [ ! -f "$HOME/.pi/agent/settings.json" ] || [ -L "$HOME/.pi/agent/settings.json" ]; then
        run rm -f "$HOME/.pi/agent/settings.json"
        run install -m 600 ${config.eminix.pi.settingsSource} "$HOME/.pi/agent/settings.json"
      fi
    '';

    # OpenRouter keys: symlink into the HM-owned ~/.pi/agent from the agenix
    # secret at /run/agenix/openrouter-auth. HM owns this dir, so there is no
    # root/user ownership collision (agenix no longer creates ~/.pi/agent).
    # .stignore already excludes /auth.json from Syncthing.
    #
    # Gated on eminix.pi.enable, NOT on "is this a NixOS host with agenix".
    # The secret itself (e.g. an OpenRouter auth key) is declared by the
    # consuming flake; this module only symlinks the decrypted secret into the
    # pi agent's home when this host actually runs pi.
    home.file.".pi/agent/auth.json" = lib.mkIf config.eminix.pi.enable {
      source = config.lib.file.mkOutOfStoreSymlink "/run/agenix/openrouter-auth";
    };

    home.file.".pi/agent/AGENTS.md" = {
      # Flake-relative path literal (not a string): the file is copied into the
      # store, so hosts without a dotfiles checkout still get it, and pure
      # evaluation works (an absolute /home/... path aborts nixos-install).
      source = ./pi/agent/AGENTS.md;
    };

    # Same reasoning as AGENTS.md above, applied to whole directories: flake-
    # relative path literals copy skills/ and extensions/ into the store, so
    # pi actually loads them (found 2026-08-07: after the stow retirement
    # these were dangling symlinks into a deleted base/pi/, and pi silently
    # loaded zero skills/extensions).
    home.file.".pi/agent/skills".source = ./pi/agent/skills;
    home.file.".pi/agent/extensions".source = ./pi/agent/extensions;

    # Pi themes are generated by bin/gen-pi-theme.py during bootstrap.
    # HM doesn't manage the generated output — the runtime theme switcher handles it.

    # Syncthing folder marker and ignore file for the ~/.pi/agent/ sync folder.
    # These live inside the folder so Syncthing recognizes it.
    home.file.".pi/agent/.stfolder" = {
      text = "";
      force = true; # Ensure it exists even if Syncthing clears it
    };

    home.file.".pi/agent/.stignore" = {
      text = ''
        // Non-portable — API keys, per-machine auth
        /auth.json

        // Owned by home-manager/stow per host (nix store symlinks on NixOS —
        // syncing these caused the settings.json sync-conflict of 2026-07-11)
        /settings.json
        /AGENTS.md
        /skills
        /extensions

        // Generated per machine by the theme switcher
        // NB: no trailing slashes — syncthing ignores are not gitignore;
        // "/npm/" matches nothing (verified 2026-07-13: dirs leaked to zord-old)
        /themes

        // Architecture-specific install artifacts — reinstall via pi packages on each machine
        /npm
        /git
        /bin

        // Local-only runtime state
        /intercom
        /chains
        /epimetheus
        /run-history.jsonl
        /extensions/pi-hindsight/queues

        // Temp files
        /settings.json.tmp
      '';
    };
  };
}