{ config, lib, pkgs, ... }:

{
  # Pi coding agent configuration.
  # Pi itself is installed via npm (not packaged in nixpkgs), so this module
  # only manages the config files. `pi` itself is installed via `npm i -g @pi/...`
  # as a post-install step (see docs/ioshi/eminix-install.md).
  # settings.json is SEEDED, not owned: pi mutates it at runtime (model
  # toggles, lastChangelogVersion), so a read-only store symlink breaks pi —
  # and without the real file's `packages` list, pi loads no extensions at
  # all (found 2026-07-13: zord-old had a {theme,model} stub → no hindsight
  # bar). After the first activation the machine's copy is authoritative;
  # it is stignored from the pi-agent sync, so per-machine drift is fine.
  home.activation.piSettingsSeed = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    if [ ! -f "$HOME/.pi/agent/settings.json" ] || [ -L "$HOME/.pi/agent/settings.json" ]; then
      run rm -f "$HOME/.pi/agent/settings.json"
      run install -m 600 ${../../base/pi/.pi/agent/settings.json} "$HOME/.pi/agent/settings.json"
    fi
  '';

  home.file.".pi/agent/AGENTS.md" = {
    # Flake-relative path literal (not a string): the file is copied into the
    # store, so hosts without a dotfiles checkout still get it, and pure
    # evaluation works (an absolute /home/... path aborts nixos-install).
    source = ../../base/pi/.pi/agent/AGENTS.md;
  };

  # Pi themes are generated by bin/gen-pi-theme.py during bootstrap.
  # HM doesn't manage the generated output — the runtime theme switcher handles it.

  # Syncthing folder marker and ignore file for the ~/.pi/agent/ sync folder.
  # These live inside the folder so Syncthing recognizes it.
  home.file.".pi/agent/.stfolder" = {
    text = "";
    force = true; # Ensure it exists even if Syncthing clears it
  };

  home.file.".pi/agent/.stignore" = {
    text = ''
      // Non-portable — API keys, per-machine auth
      /auth.json

      // Owned by home-manager/stow per host (nix store symlinks on NixOS —
      // syncing these caused the settings.json sync-conflict of 2026-07-11)
      /settings.json
      /AGENTS.md

      // Generated per machine by the theme switcher
      // NB: no trailing slashes — syncthing ignores are not gitignore;
      // "/npm/" matches nothing (verified 2026-07-13: dirs leaked to zord-old)
      /themes

      // Architecture-specific install artifacts — reinstall via pi packages on each machine
      /npm
      /git
      /bin

      // Local-only runtime state
      /intercom
      /chains
      /epimetheus
      /run-history.jsonl
      /extensions/pi-hindsight/queues

      // Temp files
      /settings.json.tmp
    '';
  };
}