{ config, ... }:

{
  programs.zsh = {
    enable = true;
    # Lock the legacy dotDir (home dir) to silence the 26.05 default-change
    # warning without moving zsh's dotfiles. Revisit (XDG) in emanix v2.
    dotDir = config.home.homeDirectory;
    enableCompletion = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;

    oh-my-zsh = {
      enable = true;
      theme = "robbyrussell";
      plugins = [
        "git"
        "sudo"
        "systemd"
        "command-not-found"
      ];
      custom = "$ZSH/custom";
    };

    sessionVariables = {
      EDITOR = "emacsclient";
      VISUAL = "emacsclient";
      PAGER = "less";
      # The emanix checkout — derives from the src option so consumers
      # (dotfiles) that check out elsewhere get the right path in elisp/shell.
      EMANIX = config.emanix.src.path;
      # Themes dir the active-theme tooling reads — generated by the distro
      # (lib/theme-tree.nix) into the store; consumers may override to point
      # elsewhere.
      EMANIX_THEMES_DIR = config.emanix.src.themesDir;
      # Helper-script dir — likewise consumer-controlled (no bin/ in the
      # distro). Read from elisp too, so it must be a session variable and
      # not merely a PATH entry.
      EMANIX_BIN_DIR = config.emanix.src.binDir;
      # Interactive convenience only — nothing in the repo reads it.
      EMANIX_ROLE = config.emanix.role;
    };

    initContent = ''
      # Prepend hostname in parentheses when SSH'd in, so you always
      # know which machine you're on.
      if [[ -n "$SSH_CLIENT" ]]; then
        PROMPT='(%m) %{$fg_bold[green]%}%p %{$fg[cyan]%}%c %{$fg_bold[blue]%}$(git_prompt_info) %{$reset_color%}'
      fi

      # Helper scripts live in the CONSUMER's checkout, not the distro's —
      # $EMANIX/bin was always a path that did not exist.
      export PATH="$EMANIX_BIN_DIR:$PATH"

      # Local bin
      export PATH="$HOME/.local/bin:$PATH"

      # fzf (installed by Nix or apt, source if available)
      if [[ -f /usr/share/fzf/key-bindings.zsh ]]; then
        source /usr/share/fzf/key-bindings.zsh
        source /usr/share/fzf/completion.zsh
      fi

      # zoxide
      if command -v zoxide &>/dev/null; then
        eval "$(zoxide init zsh)"
      fi

      # Dotfiles theme state markers
      [[ -f "$HOME/.config/dotfiles/active-theme" ]] && \
        export ACTIVE_THEME="$(cat "$HOME/.config/dotfiles/active-theme")"

      # Refresh PATH from Nix profiles on every shell
      if [[ -d /nix/var/nix/profiles/default/bin ]]; then
        export PATH="/nix/var/nix/profiles/default/bin:$PATH"
      fi

      # Starship prompt (if installed)
      if command -v starship &>/dev/null; then
        eval "$(starship init zsh)"
      fi

      # Emacs clients. ec prefers the Wayland display: pgtk emacs over X11 is
      # unsupported (warns, sporadic crashes) and picks X11 whenever $DISPLAY
      # is set — which WSLg always does alongside $WAYLAND_DISPLAY.
      ec() {
        if [[ -n "$WAYLAND_DISPLAY" ]]; then
          # WSLg's compositor can die while its socket FILES survive (seen
          # 2026-07-26). pgtk emacs KILLS THE WHOLE DAEMON when a frame
          # can't open its display, so probe liveness first: WSLg's X0
          # socket vanishes exactly when the compositor is dead.
          if [[ -d /mnt/wslg ]] && [[ ! -S /tmp/.X11-unix/X0 ]]; then
            echo "ec: WSLg display looks dead (no /tmp/.X11-unix/X0) — restart the distro:" >&2
            echo "    wsl --terminate <distro> (from PowerShell, then reopen)" >&2
            return 1
          fi
          # Rarer sibling failure: the compositor is ALIVE (X0 present, frames
          # create, frame-visible-p says t) but weston hit an I/O error mapping
          # /mnt/shared_memory at session start and so set use_gfxredir = 0 —
          # killing the channel that carries window pixels to Windows. Frames
          # then open, take focus, get a taskbar button and never paint; the
          # window title gains a "[WARN:COPY MODE]" prefix. Cost a morning on
          # 2026-08-10 because every symptom points at emacs/GlazeWM/monitors
          # instead. weston logs the value once per session and /mnt/wslg is
          # tmpfs, so this always describes the CURRENT session.
          if [[ "$(grep -a 'use_gfxredir' /mnt/wslg/weston.log 2>/dev/null | tail -1)" == *"= 0"* ]]; then
            echo "ec: WSLg has gfxredir disabled — a GUI frame would open but never paint." >&2
            echo "    weston failed to map /mnt/shared_memory when this session started." >&2
            echo "    Fix: wsl --shutdown   (from PowerShell, then reopen)" >&2
            echo "    Note: wsl --terminate is NOT enough, nor is killing msrdc.exe." >&2
            echo "    Until then use: et   (terminal frame, same daemon, unaffected)" >&2
            return 1
          fi
          emacsclient -c -d "$WAYLAND_DISPLAY" "$@"
        else
          emacsclient -c "$@"
        fi
      }
      et() { emacsclient -t "$@"; }
    '';
  };

  # The same three paths, exported to the SYSTEMD USER MANAGER as well as the
  # shell. A systemd user service does not start from a login shell, so
  # programs.zsh.sessionVariables above never reaches one — and the Emacs
  # daemon is exactly such a service. Without this, elisp that resolves
  # $EMANIX_BIN_DIR (the calendar-sync binding, the pi fallback, the EWM
  # firefox slot) gets an empty string and expands to a bare relative path.
  #
  # emanix-pi.el's fallback documents the daemon as its reason for existing,
  # so the daemon is the case that must work, not the one that may be missed.
  # Landing these here rather than in theme.nix, next to the shell exports
  # they mirror, so the two lists cannot drift apart.
  #
  # HM writes these to ~/.config/environment.d/, which the user manager reads
  # at start: changing them needs `systemctl --user daemon-reload` plus a
  # restart of the affected service, not just a rebuild.
  systemd.user.sessionVariables = {
    EMANIX = config.emanix.src.path;
    EMANIX_THEMES_DIR = config.emanix.src.themesDir;
    EMANIX_BIN_DIR = config.emanix.src.binDir;
  };
}
