# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#eff1f5"

# Main text color
theme[main_fg]="#1a1c28"

# Title color for boxes
theme[title]="#1a1c28"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#0d47a1"

# Background color of selected item in processes box
theme[selected_bg]="#bcc0cc"

# Foreground color of selected item in processes box
theme[selected_fg]="#0d47a1"

# Color of inactive/disabled text
theme[inactive_fg]="#8c8fa1"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#7a2f00"

# Background color of the percentage meters
theme[meter_bg]="#bcc0cc"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#7a2f00"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#5e1fa1" #Mauve
theme[mem_box]="#2d5016" #Green
theme[net_box]="#991122" #Maroon
theme[proc_box]="#0d47a1" #Blue

# Box divider line and small boxes line color
theme[div_line]="#9ca0b0"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#2d5016"
theme[temp_mid]="#5a3f00"
theme[temp_end]="#991122"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#054548"
theme[cpu_mid]="#0a5880"
theme[cpu_end]="#5e1fa1"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#5e1fa1"
theme[free_mid]="#5e1fa1"
theme[free_end]="#0d47a1"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#0a5880"
theme[cached_mid]="#0d47a1"
theme[cached_end]="#5e1fa1"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#7a2f00"
theme[available_mid]="#991122"
theme[available_end]="#991122"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#2d5016"
theme[used_mid]="#054548"
theme[used_end]="#0a5880"

# Download graph colors (Peach -> Red)
theme[download_start]="#7a2f00"
theme[download_mid]="#991122"
theme[download_end]="#991122"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#2d5016"
theme[upload_mid]="#054548"
theme[upload_end]="#0a5880"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#0a5880"
theme[process_mid]="#5e1fa1"
theme[process_end]="#5e1fa1"