# Catppuccin Latte; switched by theme-switch
font=JetBrainsMono Nerd Font:size=11
dpi-aware=yes
width=40
lines=10
horizontal-pad=12
vertical-pad=12
inner-pad=8

[colors]
background=eff1f5ff
text=4c4f69ff
match=d20f39ff
selection=acb0beff
selection-text=4c4f69ff
selection-match=d20f39ff
border=1e66f5ff

[border]
radius=4
width=2
