font=JetBrainsMono Nerd Font 10
background-color=#eff1f5
text-color=#1a1c28
border-color=#0d47a1
border-size=2
border-radius=4
padding=12
margin=8
default-timeout=5000
max-visible=3
layer=overlay
anchor=top-right
icon-path=/usr/share/icons/hicolor

[urgency=low]
text-color=#3c3e4f

[urgency=high]
border-color=#991122
text-color=#991122
default-timeout=0
