font=JetBrainsMono Nerd Font 10
background-color=#eff1f5
text-color=#4c4f69
border-color=#1e66f5
border-size=2
border-radius=4
padding=12
margin=8
default-timeout=5000
max-visible=3
layer=overlay
anchor=top-right
icon-path=/usr/share/icons/hicolor

[urgency=low]
text-color=#6c6f85

[urgency=high]
border-color=#d20f39
text-color=#d20f39
default-timeout=0
