{ pkgs, ... }:

rec {
  # Theme palette definitions and config generators.
  # Each theme is a palette + variant; each generator produces app config text.
  #
  # Usage from an HM module:
  #   lib.theme.generators.ghostty lib.theme.palettes.catppuccin-mocha
  #
  # Or from a host config:
  #   lib.theme.mkTheme lib.theme.palettes.catppuccin-mocha

  palettes = {
    catppuccin-mocha = {
      variant = "dark";
      colors = {
        rosewater = "#f5e0dc";
        flamingo = "#f2cdcd";
        pink = "#f5c2e7";
        mauve = "#cba6f7";
        red = "#f38ba8";
        maroon = "#eba0ac";
        peach = "#fab387";
        yellow = "#f9e2af";
        green = "#a6e3a1";
        teal = "#94e2d5";
        sky = "#89dceb";
        sapphire = "#74c7ec";
        blue = "#89b4fa";
        lavender = "#b4befe";
        text = "#cdd6f4";
        subtext1 = "#bac2de";
        subtext0 = "#a6adc8";
        overlay2 = "#9399b2";
        overlay1 = "#7f849c";
        overlay0 = "#6c7086";
        surface2 = "#585b70";
        surface1 = "#45475a";
        surface0 = "#313244";
        base = "#1e1e2e";
        mantle = "#181825";
        crust = "#11111b";
      };
    };

    catppuccin-latte = {
      variant = "light";
      colors = {
        rosewater = "#dc8a78";
        flamingo = "#dd7878";
        pink = "#ea76cb";
        mauve = "#8839ef";
        red = "#d20f39";
        maroon = "#e64553";
        peach = "#fe640b";
        yellow = "#df8e1d";
        green = "#40a02b";
        teal = "#179299";
        sky = "#04a5e5";
        sapphire = "#209fb5";
        blue = "#1e66f5";
        lavender = "#7287fd";
        text = "#4c4f69";
        subtext1 = "#5c5f77";
        subtext0 = "#6c6f85";
        overlay2 = "#7c7f93";
        overlay1 = "#8c8fa1";
        overlay0 = "#9ca0b0";
        surface2 = "#acb0be";
        surface1 = "#bcc0cc";
        surface0 = "#ccd0da";
        base = "#eff1f5";
        mantle = "#e6e9ef";
        crust = "#dce0e8";
      };
    };
  };

  # Generates text suitable for a Ghostty config file.
  ghostty = palette: ''
    # Generated by dotfiles/lib/themes.nix — ${palette.variant} variant
    background = ${palette.colors.base}
    foreground = ${palette.colors.text}

    cursor-color = ${palette.colors.rosewater}
    cursor-text = ${palette.colors.crust}

    selection-background = ${palette.colors.surface0}
    selection-foreground = ${palette.colors.text}

    palette = 0=${palette.colors.surface1}
    palette = 1=${palette.colors.red}
    palette = 2=${palette.colors.green}
    palette = 3=${palette.colors.yellow}
    palette = 4=${palette.colors.blue}
    palette = 5=${palette.colors.pink}
    palette = 6=${palette.colors.teal}
    palette = 7=${palette.colors.subtext0}
    palette = 8=${palette.colors.surface2}
    palette = 9=${palette.colors.red}
    palette = 10=${palette.colors.green}
    palette = 11=${palette.colors.yellow}
    palette = 12=${palette.colors.blue}
    palette = 13=${palette.colors.pink}
    palette = 14=${palette.colors.teal}
    palette = 15=${palette.colors.subtext1}
  '';

  # Generates the `source =` block for Hyprland theme.conf.
  hyprland = palette: ''
    # Generated by dotfiles/lib/themes.nix — ${palette.variant} variant
    $col_active = rgb(${builtins.substring 1 6 palette.colors.blue})
    $col_inactive = rgba(00000000)
  '';

  # Generates Mako config text.
  mako = palette: ''
    # Generated by dotfiles/lib/themes.nix — ${palette.variant} variant
    background-color=${palette.colors.base}
    text-color=${palette.colors.text}
    border-color=${palette.colors.blue}
    font=JetBrainsMono Nerd Font 10
    border-size=2
    border-radius=4
    padding=12
    margin=8
    default-timeout=5000
    max-visible=3
    layer=overlay
    anchor=top-right

    [urgency=high]
    border-color=${palette.colors.red}
    default-timeout=0
  '';

  # Generates Waybar CSS.
  waybarCSS = palette: ''
    /* Generated by dotfiles/lib/themes.nix — ${palette.variant} variant */
    * {
        font-family: "JetBrainsMono Nerd Font", monospace;
        font-size: 12px;
        min-height: 0;
    }

    window#waybar {
        background: rgba(${
          builtins.substring 1 2 palette.colors.base
        }, ${
          builtins.substring 3 2 palette.colors.base
        }, ${
          builtins.substring 5 2 palette.colors.base
        }, 0.9);
        color: ${palette.colors.text};
        border-bottom: 2px solid rgba(${
          builtins.substring 1 2 palette.colors.blue
        }, ${
          builtins.substring 3 2 palette.colors.blue
        }, ${
          builtins.substring 5 2 palette.colors.blue
        }, 0.3);
    }
    /* NOTE: full waybar CSS from base/waybar/.config/waybar/style.css
       will be ported here when the waybar.nix module is written. */
  '';

  # swaylock config (colors are RRGGBB[AA], no leading '#').
  # Ring/text states follow upstream catppuccin/swaylock conventions.
  swaylock = palette:
    let c = name: builtins.substring 1 6 palette.colors.${name};
    in ''
      ignore-empty-password
      indicator-radius=100
      indicator-idle-visible
      color=${c "crust"}
      inside-color=${c "base"}
      inside-clear-color=${c "base"}
      inside-ver-color=${c "base"}
      inside-wrong-color=${c "base"}
      ring-color=${c "lavender"}
      ring-clear-color=${c "rosewater"}
      ring-caps-lock-color=${c "peach"}
      ring-ver-color=${c "blue"}
      ring-wrong-color=${c "maroon"}
      key-hl-color=${c "green"}
      bs-hl-color=${c "rosewater"}
      text-color=${c "text"}
      text-clear-color=${c "rosewater"}
      text-caps-lock-color=${c "peach"}
      text-ver-color=${c "blue"}
      text-wrong-color=${c "maroon"}
      line-color=00000000
      line-clear-color=00000000
      line-ver-color=00000000
      line-wrong-color=00000000
      separator-color=00000000
    '';

  # Given a palette, produce the full theme config set.
  mkTheme = palette: {
    ghostty = ghostty palette;
    hyprland = hyprland palette;
    mako = mako palette;
    swaylock = swaylock palette;
    waybarCSS = waybarCSS palette;
    variant = palette.variant;
    colors = palette.colors;
  };
}
