# Zenbones Light color scheme

foreground #2C363C
background #F0EDEC
background_opacity 1.0

# Black
color0  #F0EDEC
color8  #CFC1BA

# Red
color1  #A8334C
color9  #94253E

# Green
color2  #4F6C31
color10 #3F5A22

# Yellow
color3  #944927
color11 #803D1C

# Blue
color4  #286486
color12 #1D5573

# Magenta
color5  #88507D
color13 #7B3B70

# Cyan
color6  #3B8992
color14 #2B747C

# White
color7  #2C363C
color15 #4F5E68

# Cursor
cursor #2C363C
cursor_text_color #F0EDEC

# Selection
selection_foreground #2C363C
selection_background #CBD9E3

# URL
url_color #286486

# Tab bar
active_tab_foreground   #2C363C
active_tab_background   #DEB9D6
inactive_tab_foreground #2C363C
inactive_tab_background #D6CDC9

# Window border
active_border_color #286486
inactive_border_color #CFC1BA
