# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#f2f2f2"

# Main text color
theme[main_fg]="#111111"

# Title color for boxes
theme[title]="#111111"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#0043a8"

# Background color of selected item in processes box
theme[selected_bg]="#c4c4c4"

# Foreground color of selected item in processes box
theme[selected_fg]="#0043a8"

# Color of inactive/disabled text
theme[inactive_fg]="#4a4a4a"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#8a3324"

# Background color of the percentage meters
theme[meter_bg]="#c4c4c4"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#8a3324"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#6b21a8" #Mauve
theme[mem_box]="#0d5e1b" #Green
theme[net_box]="#96001a" #Maroon
theme[proc_box]="#0043a8" #Blue

# Box divider line and small boxes line color
theme[div_line]="#515151"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#0d5e1b"
theme[temp_mid]="#654d00"
theme[temp_end]="#a70019"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#005a56"
theme[cpu_mid]="#00567a"
theme[cpu_end]="#3b3ba8"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#6b21a8"
theme[free_mid]="#3b3ba8"
theme[free_end]="#0043a8"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#00567a"
theme[cached_mid]="#0043a8"
theme[cached_end]="#3b3ba8"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#804000"
theme[available_mid]="#96001a"
theme[available_end]="#a70019"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#0d5e1b"
theme[used_mid]="#005a56"
theme[used_end]="#005776"

# Download graph colors (Peach -> Red)
theme[download_start]="#804000"
theme[download_mid]="#96001a"
theme[download_end]="#a70019"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#0d5e1b"
theme[upload_mid]="#005a56"
theme[upload_end]="#005776"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#00567a"
theme[process_mid]="#3b3ba8"
theme[process_end]="#6b21a8"