{ config, lib, pkgs, ... }:

{
  boot.kernelParams = [ "quiet" ];
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  # Init amdgpu in the initrd so the Radeon 780M is up before userspace —
  # EWM launches from tty1 autologin and loses the DRM-master race otherwise
  # (verified on zord-old).
  boot.initrd.kernelModules = [ "amdgpu" ];
  hardware.enableRedistributableFirmware = true;

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Disk layout (fileSystems + boot.initrd.luks.devices) is GENERATED by the
  # disko module from hosts/zord/disko.nix. Do NOT hand-write it here — a
  # second definition collides with disko's by-partlabel paths and the whole
  # config fails to evaluate. This file is hardware only.

  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
    jack.enable = true;
  };
  hardware.bluetooth.enable = true;
  services.libinput.enable = true;
  powerManagement.enable = true;
  services.power-profiles-daemon.enable = true;
}
