{ config, lib, pkgs, ... }:

{
  # Pi coding agent configuration.
  # Pi itself is installed via npm (not packaged in nixpkgs), so this module
  # only manages the config files. The actual install happens during bootstrap
  # (install/07-pi.sh for Phase 1; a post-install hook for Phase 2).
  home.file.".pi/agent/settings.json" = {
    text = builtins.toJSON {
      theme = config.scott.theme;
      model = "gemini-2.5-flash";
      # Other settings from base/pi/ go here
    };
  };

  home.file.".pi/agent/AGENTS.md" = {
    # Flake-relative path literal (not a string): the file is copied into the
    # store, so hosts without a dotfiles checkout still get it, and pure
    # evaluation works (an absolute /home/... path aborts nixos-install).
    source = ../../base/pi/.pi/agent/AGENTS.md;
  };

  # Pi themes are generated by bin/gen-pi-theme.py during bootstrap.
  # HM doesn't manage the generated output — the runtime theme switcher handles it.

  # Syncthing folder marker and ignore file for the ~/.pi/agent/ sync folder.
  # These live inside the folder so Syncthing recognizes it.
  home.file.".pi/agent/.stfolder" = {
    text = "";
    force = true; # Ensure it exists even if Syncthing clears it
  };

  home.file.".pi/agent/.stignore" = {
    text = ''
      // Non-portable — API keys, per-machine auth
      /auth.json

      // Owned by home-manager/stow per host (nix store symlinks on NixOS —
      // syncing these caused the settings.json sync-conflict of 2026-07-11)
      /settings.json
      /AGENTS.md

      // Generated per machine by the theme switcher
      /themes/

      // Architecture-specific install artifacts — reinstall via pi packages on each machine
      /npm/
      /git/
      /bin/

      // Local-only runtime state
      /intercom/
      /chains/
      /epimetheus/
      /run-history.jsonl

      // Temp files
      /settings.json.tmp
    '';
  };
}