{ config, lib, pkgs, ... }:

{
  programs.waybar = {
    enable = true;
    systemd.enable = true;

    settings = {
      mainBar = {
        layer = "top";
        position = "top";
        height = 30;
        spacing = 4;
        modules-left = [ "hyprland/workspaces" "hyprland/mode" ];
        modules-center = [ "hyprland/window" ];
        modules-right = [
          "cpu"
          "memory"
          "network"
          "pulseaudio"
          "clock"
          "tray"
        ];

        "hyprland/workspaces" = {
          disable-scroll = true;
          all-outputs = false;
          format = "{name}";
          format-icons = {
            "1" = "1";
            "2" = "2";
            "3" = "3";
            "4" = "4";
            "5" = "5";
            "6" = "6";
            "7" = "7";
            "8" = "8";
            "9" = "9";
            "10" = "10";
          };
        };

        clock = {
          format = "{:%H:%M  %a %d %b}";
          tooltip-format = "{:%A, %d %B %Y %H:%M}";
          interval = 60;
        };

        cpu = {
          format = "CPU {usage}%";
          interval = 5;
        };

        memory = {
          format = "RAM {}%";
          interval = 30;
        };

        network = {
          format-wifi = "  {signalStrength}%";
          format-ethernet = "󰈀  {ifname}";
          format-disconnected = "⚠ Disconnected";
          tooltip-format = "{ifname} via {gwaddr}";
          interval = 30;
        };

        pulseaudio = {
          format = "{volume}% {icon}";
          format-muted = " 0%";
          format-icons = {
            default = [ "" "" "" ];
          };
          on-click = "pavucontrol";
          scroll-step = 5;
        };

        tray = {
          spacing = 10;
        };
      };
    };

    style = ''
      /* style.css is generated by dot-theme-set and symlinked in.
         This file just provides the base structure. The theme module
         writes the actual colors to ~/.config/waybar/style.css */
      @import url("theme.css");
    '';
  };
}